var index = [
{'name': 'io.github.weakish.zhihu', 'type': 'package', 'url': 'index.html#section-package', 'doc': '<p>Readonly API client of zhuanlan.zhihu.com</p>', 'tags': [],'icons': ['icon-package']},
{'name': 'run', 'type': 'function', 'url': 'index.html#run', 'doc': '<p>Run the module <code>io.github.weakish.zhihu</code>.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'fetchColumnInfo', 'type': 'function', 'url': 'index.html#fetchColumnInfo', 'doc': '<p>Returns column info json string.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'fetchComments', 'type': 'function', 'url': 'index.html#fetchComments', 'doc': '<p>Fetch comments json files, named `POST_SLUG_comments.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'titleImageUrl', 'type': 'function', 'url': 'index.html#titleImageUrl', 'doc': '<p><code>titleImage</code> may be an empty string (&ldquo;&ldquo;).</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'titleImagesUrls', 'type': 'function', 'url': 'index.html#titleImagesUrls', 'doc': '<p>Skip posts which can not be parsed as JsonObject, or does not contain title Image.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'Tasks', 'type': 'alias', 'url': 'index.html#Tasks', 'doc': '<p>task pool</p>', 'tags': [],'icons': ['icon-type-alias']},
{'name': 'fetchTitleImages', 'type': 'function', 'url': 'index.html#fetchTitleImages', 'doc': '<p>Fetch title images, non blocking.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'contentImage', 'type': 'function', 'url': 'index.html#contentImage', 'doc': '<p>Parse post content for image urls.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'content', 'type': 'function', 'url': 'index.html#content', 'doc': '<p>Extract post content.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'contents', 'type': 'function', 'url': 'index.html#contents', 'doc': '<p>Map content(post) over posts.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'urlify', 'type': 'function', 'url': 'index.html#urlify', 'doc': '<p>Urlify images hosted by zhihu CDN.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'fetchFileSync', 'type': 'function', 'url': 'index.html#fetchFileSync', 'doc': '<p>Like <a class=\'link\' href=\'index.html#fetchFile\' title=\'Go to io.github.weakish.zhihu::fetchFile\'><code><span class=\'identifier\'>fetchFile()</span></code></a> but blocking.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'fetchContentImages', 'type': 'function', 'url': 'index.html#fetchContentImages', 'doc': '<p>Return a list of <code>[exitCode, failedUrl]</code>.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'checkTasks', 'type': 'function', 'url': 'index.html#checkTasks', 'doc': '<p>Check tasks, return a tuple of [Unfinished, Failed] tasks.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'parseColumnInfo', 'type': 'function', 'url': 'index.html#parseColumnInfo', 'doc': '<p>Parse columninfo json string for postsCount, urls of avatar and creatorAvatar.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'fetchFile', 'type': 'function', 'url': 'index.html#fetchFile', 'doc': '<p>Fetch file via wget, non blocking.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'fetchAvatarFiles', 'type': 'function', 'url': 'index.html#fetchAvatarFiles', 'doc': '<p>Non blocking.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'writeFile', 'type': 'function', 'url': 'index.html#writeFile', 'doc': '<p>Write a String to a filePath,\nif filePath already exist, write to filePath_SHA256</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'fetchPosts', 'type': 'function', 'url': 'index.html#fetchPosts', 'doc': '<p>Returns a json string and saves to <code>COLUMN_NAME_posts.json</code>.</p>', 'tags': ['TODO'],'icons': ['icon-shared-member']},
{'name': 'column', 'type': 'function', 'url': 'index.html#column', 'doc': '<p>Return full column url.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'posts', 'type': 'function', 'url': 'index.html#posts', 'doc': '<p>Return posts url.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'comments', 'type': 'function', 'url': 'index.html#comments', 'doc': '<p>Return url of comments of a single post.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'getContent', 'type': 'function', 'url': 'index.html#getContent', 'doc': '<p>Given a Uri, get Response content, following one direct.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'getJsonValue', 'type': 'function', 'url': 'index.html#getJsonValue', 'doc': '<p>Returns JsonObject[key] else null.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'getColumn', 'type': 'function', 'url': 'index.html#getColumn', 'doc': '<p>Non ascii characters are always 16 bit encoded, e.g. <code></code></p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'avatarUrl', 'type': 'function', 'url': 'index.html#avatarUrl', 'doc': '<p>Parse <code>columnInfo</code> or <code>creator</code> for avatar url.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'KeyNotFound', 'type': 'class', 'url': 'KeyNotFound.type.html', 'doc': '<p>When not satisfied with just returnning null.</p>', 'tags': [],'icons': ['icon-class']},
{'name': 'postsCount', 'type': 'function', 'url': 'index.html#postsCount', 'doc': '<p>Given a column info, returns postsCount.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'getPosts', 'type': 'function', 'url': 'index.html#getPosts', 'doc': '<p>Get posts belong to a column, including post content, without comments.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'slug', 'type': 'function', 'url': 'index.html#slug', 'doc': '<p>Zhihu uses Integer for post slug.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'slugs', 'type': 'function', 'url': 'index.html#slugs', 'doc': '<p>Map slug(post) over posts.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'getComments', 'type': 'function', 'url': 'index.html#getComments', 'doc': '<p>Returns comments json string of a single post.</p>', 'tags': [],'icons': ['icon-shared-member']},
{'name': 'io.github.weakish.zhihu', 'type': 'module', 'url': 'index.html', 'doc': '<p>A client to zhihu.com API.</p>', 'tags': [],'icons': ['icon-module']}];
var tagIndex = [
'TODO'];
